--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/skyss0fly/WelcomeMessage
build-by-default: true
branches:
- main
projects:
  WelcomeMessage:
    path: ""
    icon: "Icon.png"
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
...
